// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID        int32       `json:"id"`
	Fullname  string      `json:"fullname"`
	Nickname  string      `json:"nickname"`
	Username  string      `json:"username"`
	Email     string      `json:"email"`
	Password  string      `json:"password"`
	Role      interface{} `json:"role"`
	Age       int32       `json:"age"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type Category struct {
	ID        int32     `json:"id"`
	Type      string    `json:"type"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	DeletedAt time.Time `json:"deleted_at"`
}

type Ticket struct {
	ID          int32        `json:"id"`
	CategoryID  int32        `json:"category_id"`
	Title       string       `json:"title"`
	Description string       `json:"description"`
	Price       float64      `json:"price"`
	Seat        int32        `json:"seat"`
	Duration    sql.NullTime `json:"duration"`
	BookedAt    time.Time    `json:"booked_at"`
	CreatedAt   time.Time    `json:"created_at"`
	DeletedAt   time.Time    `json:"deleted_at"`
}
